all : Fig1a   Fig2a   Fig2b   Sol1a   Sol1b   Sol2a   Sol2b \
      Fig1a_e Fig2a_e Fig2b_e Sol1a_e Sol1b_e Sol2a_e Sol2b_e \

clean_all:
	rm Fig1a   Fig2a   Fig2b   Sol1a   Sol1b   Sol2a   Sol2b \
	   Fig1a_e Fig2a_e Fig2b_e Sol1a_e Sol1b_e Sol2a_e Sol2b_e



Fig1a: Fig1a.c
Fig2a: Fig2a.c
Fig2b: Fig2b.c

Sol1a: Sol1a.c
Sol1b: Sol1b.c
Sol2a: Sol2a.c
Sol2b: Sol2b.c



Fig1a_e: Fig1a_e.c
Fig2a_e: Fig2a_e.c
Fig2b_e: Fig2b_e.c

Sol1a_e: Sol1a_e.c
Sol1b_e: Sol1b_e.c
Sol2a_e: Sol2a_e.c
Sol2b_e: Sol2b_e.c